In [3]:
import pandas as pd
import matplotlib.pyplot as mpl
import seaborn as sns

In [10]:
df = pd.read_csv('customer_shopping_data.csv')

In [11]:
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon

In [14]:
df.shape

(99457, 10)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   gender          99457 non-null  object
 3   age             99457 non-null  int64
 4   category        99457 non-null  object
 5   quantity        99457 non-null  int64
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  object
 8   invoice_date    99457 non-null  object
 9   shopping_mall   99457 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 7.6+ MB

In [17]:
df.isnull().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [20]:
df['invoice_date'] = pd.to_datetime(df['invoice_date'], dayfirst=True)

In [21]:
df['year'] = df['invoice_date'].dt.year
df['month'] = df['invoice_date'].dt.month

In [25]:
df[['invoice_date','year','month']].head()
df['year'].unique()

array([2022, 2021, 2023])

In [31]:
df.head(10)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,year,month
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,2022,8
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,2021,12
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity,2021,11
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,2021,5
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,2021,10
5,I227836,C657758,Female,28,Clothing,5,1500.40,Credit Card,2022-05-24,Forum Istanbul,2022,5
6,I121056,C151197,Female,49,Cosmetics,1,40.66,Cash,2022-03-13,Istinye Park,2022,3
7,I293112,C176086,Female,32,Clothing,2,600.16,Credit Card,2021-01-13,Mall of Istanbul,2021,1
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,2021-11-04,Metrocity,2021,11
9,I326945,C283361,Female,60,Clothing,2,600.16,Credit Card,2021-08-22,Kanyon,2021,8

In [36]:
df.groupby('category')['price'].sum().sort_values(ascending=False)

category
Clothing           31075684.64
Shoes              18135336.89
Technology         15772050.00
Cosmetics           1848606.90
Toys                1086704.64
Food & Beverage      231568.71
Books                226977.30
Souvenir             174436.83
Name: price, dtype: float64

In [37]:
df.groupby('shopping_mall')['price'].sum().sort_values(ascending=False)

shopping_mall
Mall of Istanbul     13851737.62
Kanyon               13710755.24
Metrocity            10249980.07
Metropol AVM          6937992.99
Istinye Park          6717077.54
Zorlu Center          3509649.02
Cevahir AVM           3433671.84
Viaport Outlet        3414019.46
Emaar Square Mall     3390408.31
Forum Istanbul        3336073.82
Name: price, dtype: float64

In [38]:
df.groupby('payment_method')['price'].sum().sort_values(ascending=False)

payment_method
Cash           30705030.98
Credit Card    24051476.93
Debit Card     13794858.00
Name: price, dtype: float64

In [39]:
df.groupby('gender')['price'].sum().sort_values(ascending=False)

gender
Female    40931801.62
Male      27619564.29
Name: price, dtype: float64

In [50]:
df.groupby('category')['price'].mean().sort_values(ascending=False)

category
Technology         3156.935548
Shoes              1807.388568
Clothing            901.084021
Cosmetics           122.448626
Toys                107.733185
Books                45.568621
Souvenir             34.894345
Food & Beverage      15.671948
Name: price, dtype: float64

In [54]:
 df.groupby('category')['price'].mean().sort_values(ascending=False)

category
Technology         3156.935548
Shoes              1807.388568
Clothing            901.084021
Cosmetics           122.448626
Toys                107.733185
Books                45.568621
Souvenir             34.894345
Food & Beverage      15.671948
Name: price, dtype: float64

In [63]:
pivot_price = pd.pivot_table(df,values='price',index='shopping_mall',columns='category', aggfunc='sum')
pivot_price.index.name = None
pivot_price.columns.name = None

In [61]:
display(pivot_df)

,Books,Clothing,Cosmetics,Food & Beverage,Shoes,Souvenir,Technology,Toys
Cevahir AVM,11998.80,1554414.40,88394.84,11992.39,884050.41,8304.84,819000.0,55516.16
Emaar Square Mall,11059.50,1511803.04,92379.52,11030.07,871446.84,8515.98,834750.0,49423.36
Forum Istanbul,11453.40,1572119.12,95225.72,10836.56,875648.03,9090.75,706650.0,55050.24
Istinye Park,20725.20,3050313.20,178741.36,23419.94,1806511.70,18369.18,1509900.0,109096.96
Kanyon,44980.35,6155541.04,372242.30,45474.85,3640031.05,35483.25,3202500.0,214502.40
Mall of Istanbul,46949.85,6245565.04,373787.38,46431.94,3668239.04,34263.33,3220350.0,216151.04
Metrocity,34405.65,4719958.32,272422.00,35375.72,2610139.33,25770.81,2386650.0,165258.24
Metropol AVM,22240.20,3166444.16,185775.54,23984.78,1942750.29,18603.78,1465800.0,112394.24
Viaport Outlet,10908.00,1530708.08,92664.14,11432.78,882850.07,7636.23,823200.0,54620.16
Zorlu Center,12256.35,1568818.24,96974.10,11589.68,953670.13,8398.68,803250.0,54691.84

In [65]:
yearly_category = pd.pivot_table(df,values='price',index='year',columns='category',aggfunc='sum')
yearly_category.index.name = None
yearly_category.columns.name = None

In [66]:
display(yearly_category)

,Books,Clothing,Cosmetics,Food & Beverage,Shoes,Souvenir,Technology,Toys
2021,100065.75,14365129.68,828081.56,106179.46,8242134.61,79118.85,7104300.0,491294.72
2022,106822.65,14070451.12,855405.08,105876.12,8378373.20,80948.73,7268100.0,506849.28
2023,20088.90,2640103.84,165120.26,19513.13,1514829.08,14369.25,1399650.0,88560.64

In [67]:
gender_category = pd.pivot_table(df,values='price',index='category',columns='gender',aggfunc='sum')
gender_category.index.name = None
gender_category.columns.name = None

In [68]:
display(gender_category)

                      Female         Male
Books              132956.40     94020.90
Clothing         18616663.12  12459021.52
Cosmetics         1108432.26    740174.64
Food & Beverage    137873.26     93695.45
Shoes            10746644.02   7388692.87
Souvenir           105288.48     69148.35
Technology        9425850.00   6346200.00
Toys               658094.08    428610.56

In [69]:
category_payment = df.groupby(['category', 'payment_method']).size().reset_index(name='count')

dominant_payment = category_payment.loc[category_payment.groupby('category')['count'].idxmax()]

print(dominant_payment)

           category payment_method  count
0             Books           Cash   2268
3          Clothing           Cash  15456
6         Cosmetics           Cash   6674
9   Food & Beverage           Cash   6587
12            Shoes           Cash   4474
15         Souvenir           Cash   2211
18       Technology           Cash   2235
21             Toys           Cash   4542

In [70]:
category_payment = df.groupby(['category', 'payment_method']).size().reset_index(name='count')

In [71]:
print(category_payment)

           category payment_method  count
0             Books           Cash   2268
1             Books    Credit Card   1696
2             Books     Debit Card   1017
3          Clothing           Cash  15456
4          Clothing    Credit Card  12025
5          Clothing     Debit Card   7006
6         Cosmetics           Cash   6674
7         Cosmetics    Credit Card   5336
8         Cosmetics     Debit Card   3087
9   Food & Beverage           Cash   6587
10  Food & Beverage    Credit Card   5250
11  Food & Beverage     Debit Card   2939
12            Shoes           Cash   4474
13            Shoes    Credit Card   3553
14            Shoes     Debit Card   2007
15         Souvenir           Cash   2211
16         Souvenir    Credit Card   1770
17         Souvenir     Debit Card   1018
18       Technology           Cash   2235
19       Technology    Credit Card   1753
20       Technology     Debit Card   1008
21             Toys           Cash   4542
22             Toys    Credit Card   3548
23             Toys     Debit Card   1997